# Generated by Django 2.1.3 on 2018-11-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181121_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starttime',
        ),
    ]
