# Generated by Django 2.1.3 on 2018-11-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181121_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
